[project]
name = "mcp-server-weather"
version = "0.1.0"
description = "An MCP Server for weather"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.4",
    "fastapi>=0.115.0",
    "uvicorn>=0.32.0",
]
